added realsense support

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,8 +1,5 @@
 #!/usr/bin/env bash
 
-#TODO: 1. Shift github repo from grassjelly to linorobot
-#      2. Omit checking out to devel branch once devel is merged to master
-
 set -e
 
 sudo cp files/49-teensy.rules /etc/udev/rules.d/
@@ -42,12 +39,18 @@ if [ "$3" != "test" ]
                 echo
                 exit 1
 
-        elif [[ "$2" != "xv11" && "$2" != "rplidar" ]]
+        elif [[ "$2" != "xv11" && "$2" != "rplidar" && "$2" != "kinect" && "$2" != "realsense" ]]
             then
-                echo "Invalid linorobot sensor: $2. Setting to default: xv11"
-                LIDAR=xv11
+                echo "Invalid linorobot base: $2"
+                echo
+                echo "Valid Options:"
+                echo "xv11"
+                echo "rplidar"
+                echo "kinect"
+                echo "realsense"
+                echo
+                exit 1
         fi
-
 
         echo
         echo -n "You are installing ROS-$ROSDISTRO Linorobot for $BASE base with a $SENSOR sensor. Enter [y] to continue. " 
@@ -91,6 +94,11 @@ if [[ "$SENSOR" == "xv11" || "$3" == "test" ]]
 elif [[ "$SENSOR" == "kinect" || "$3" == "test" ]]
     then
         sudo apt-get install -y ros-$ROSDISTRO-freenect-launch
+        sudo apt-get install -y ros-$ROSDISTRO-pointcloud_to_laserscan
+
+elif [[ "$SENSOR" == "realsense" || "$3" == "test" ]]
+    then
+        sudo apt-get install -y ros-$ROSDISTRO-realsense_camera
         sudo apt-get install -y ros-$ROSDISTRO-depthimage-to-laserscan
 fi
 
